VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ICreateYoushiki"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@folder("view")
Option Explicit

Private Sub 原紙エクセルを開く()
End Sub

Private Sub 原紙ファイル初期化()
End Sub

Public Sub 一覧作成(company_ As Company, workers_ As Workers)
End Sub

Private Sub 元シートコピー()
End Sub

Private Sub 鑑作成()
End Sub

Private Sub 最終ページ作成()
End Sub

Private Sub 対象者出力(ByVal worker_index As Long, ByVal offset As Long)
End Sub
